# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Steet_address', models.CharField(max_length=120)),
                ('Litres', models.CharField(choices=[(b'40Ltrs', b'40Ltrs'), (b'60Ltrs', b'60Ltrs'), (b'80Ltrs', b'80Ltrs'), (b'100Ltrs', b'100Ltrs'), (b'120Ltrs', b'120Ltrs'), (b'140Ltrs', b'140Ltrs'), (b'160Ltrs', b'160Ltrs'), (b'180Ltrs', b'180Ltrs'), (b'200Ltrs', b'200Ltrs')], default=b'', max_length=120)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='customers',
        ),
    ]
