# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20190617_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Litres',
            field=models.CharField(choices=[(b'40Ltrs', b'40Ltrs'), (b'60Ltrs', b'60Ltrs'), (b'80Ltrs', b'80Ltrs'), (b'100Ltrs', b'100Ltrs'), (b'120Ltrs', b'120Ltrs'), (b'140Ltrs', b'140Ltrs'), (b'160Ltrs', b'160Ltrs'), (b'180Ltrs', b'180Ltrs'), (b'200Ltrs', b'200Ltrs')], default=b'40Ltrs', max_length=120),
        ),
    ]
