# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20190617_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Steet_address',
            new_name='Street_address',
        ),
    ]
