# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Street_addres',
            new_name='Street_address',
        ),
    ]
